version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/cdk_db?schema=public
      - WX_APPID=${WX_APPID}
      - WX_SECRET=${WX_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cdk_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: